function filtred = BandPass4ndOrderButter(original_signal, N, Fc1, Fc2, Fs)
    %BANDPASS2NDORDERBUTTER Returns a discrete-time filter object.

    % MATLAB Code
    % Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
    % Generated on: 31-Oct-2020 18:13:48

    % Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

    % All frequency values are in Hz.
%     Fs = 256;  % Sampling Frequency

    % Construct an FDESIGN object and call its BUTTER method.
    h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
    Hd = design(h, 'butter');

    n_channels = size(original_signal,1);
    signal_length = size(original_signal,2);
    n_traials = size(original_signal,3);
    filtred = zeros(n_channels, signal_length,n_traials);
    
    for i = 1: n_channels
        for j=1:n_traials
            filtred(i,:,j) = ...
                filter(Hd, original_signal(i,:,j));
        end
    end

end
